# Generated by Django 5.1.6 on 2025-02-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Yarışma', 'verbose_name_plural': 'Yarışmalar'},
        ),
        migrations.AlterModelOptions(
            name='contestant',
            options={'verbose_name': 'Katılımcı', 'verbose_name_plural': 'Katılımcılar'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grup', 'verbose_name_plural': 'Gruplar'},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'verbose_name': 'Hakem', 'verbose_name_plural': 'Hakemler'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': 'Sıralama', 'verbose_name_plural': 'Sıralamalar'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Etap', 'verbose_name_plural': 'Etaplar'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Yarışma Adı'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participant_count',
            field=models.PositiveIntegerField(verbose_name='Katılımcı Sayısı'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='round_details',
            field=models.JSONField(verbose_name='Tur Detayları'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='stage_count',
            field=models.PositiveIntegerField(verbose_name='Etap Sayısı'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='competitions.competition', verbose_name='Yarışma'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Katılımcı Adı'),
        ),
        migrations.AlterField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competitions.competition', verbose_name='Yarışma'),
        ),
        migrations.AlterField(
            model_name='group',
            name='contestants',
            field=models.ManyToManyField(related_name='groups', to='competitions.contestant', verbose_name='Katılımcılar'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.PositiveIntegerField(verbose_name='Grup Numarası'),
        ),
        migrations.AlterField(
            model_name='group',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competitions.stage', verbose_name='Etap'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='competitions.competition', verbose_name='Yarışma'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Hakem Adı'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.group', verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.judge', verbose_name='Hakem'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='rank',
            field=models.JSONField(verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='competitions.competition', verbose_name='Yarışma'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='group_size',
            field=models.PositiveIntegerField(verbose_name='Grup Boyutu'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_number',
            field=models.PositiveIntegerField(verbose_name='Etap Numarası'),
        ),
    ]
