# Generated by Django 5.1.6 on 2025-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='final_position',
        ),
        migrations.AddField(
            model_name='competitionparticipation',
            name='final_position',
            field=models.PositiveIntegerField(blank=True, help_text='Bu yarışmadaki final sıralaması', null=True, verbose_name='Final Sıralaması'),
        ),
    ]
