# Generated by Django 5.1.6 on 2025-02-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competition_options_alter_contestant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='round_details',
        ),
    ]
