# Generated by Django 5.1.6 on 2025-02-22 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_participant_final_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='Jüri'),
        ),
        migrations.AddField(
            model_name='competition',
            name='juries',
            field=models.ManyToManyField(blank=True, related_name='competitions_as_jury', to=settings.AUTH_USER_MODEL, verbose_name='Jüri Üyeleri'),
        ),
        migrations.DeleteModel(
            name='Jury',
        ),
    ]
