# Generated by Django 5.1.6 on 2025-02-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_remove_competition_round_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='password',
            field=models.CharField(default='123', max_length=255, verbose_name='Hakem Şifresi'),
        ),
        migrations.AddField(
            model_name='stage',
            name='contestants_to_next_stage',
            field=models.PositiveIntegerField(default=0, verbose_name='Sonraki Etapa Geçecek Katılımcı Sayısı'),
        ),
    ]
