# Generated by Django 5.1.6 on 2025-02-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_judge_password_stage_contestants_to_next_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='contestants_to_next_stage',
            field=models.PositiveIntegerField(verbose_name='Sonraki Etapa Geçecek Katılımcı Sayısı'),
        ),
    ]
