# Generated by Django 5.1.6 on 2025-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_stage_contestants_to_next_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Etap Tamamlandı'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Etap Numarası'),
        ),
    ]
