# Generated by Django 5.1.6 on 2025-02-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_stage_is_completed_alter_stage_stage_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='is_completed',
        ),
    ]
