# Generated by Django 5.1.6 on 2025-02-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_remove_stage_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_grouped',
            field=models.BooleanField(default=False, verbose_name='Gruplar Oluşturuldu mu?'),
        ),
    ]
