# Generated by Django 5.1.6 on 2025-02-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_stage_is_grouped'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('group', 'judge')},
        ),
    ]
