# Generated by Django 5.1.6 on 2025-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_ranking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Etap bitti mi'),
        ),
    ]
